name: Events Demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main # Note - this refers to the target branch of the PR, not the source branch
      - 'dev-*' # dev-new, dev-this-is-new, NOT dev-/new
      - 'feature/**' # feature/new, feature/new/button
    paths-ignore: 
      - '.github/workflows/*' # Workflow changes should not trigger themselves (handy once the workflow is stable)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
